#
# simulates a build workflow
# this workflow will run when a pull request is created
# it will sleep for a period of time and then pass or fail based on the content of the build.result.txt file.
# if there is no build.result.txt file, the workflow will pass.
#

name: Build

on:
  merge_group:
  pull_request:    

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: Wait for 9 minutes in merge queue
        if: ${{ github.event_name == 'merge_group' }}
        run: sleep 540

      - name: Pass immediately for pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "Pull request event passing immediately"
